apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 4000        # The port the service will expose
      targetPort: 4000  # The port your application listens on
  type: NodePort         # Change to 'ClusterIP' if only internal access is needed
